### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by arielp1** [taylorgrant/sandbox#2]
Hi,

Why when i run the script below i get the below error message:

```
# genesis for data ID
dms <- dmGet()
x <- dms[[1]]
id1 <- data.frame(id1 = as.numeric(x$getId()))
write_tsv(id1, "path/to/id1")
```

> dms <- dmGet()
> x <- dms[[1]]
> Error in dms[[1]] : subscript out of bounds
> id1 <- data.frame(id1 = as.numeric(x$getId()))
> Error in data.frame(id1 = as.numeric(x$getId())) : object 'x' not found

Thanks
Ariel

**Comment by taylorgrant** [comment]
Hi Ariel,

The dmGet function pulls the DMs that your Twitter account has received. If you're getting an error message, my guess is that the Twitter account you've authorized hasn't received any DMs yet. Try DMing your authorized account and then rerun. 

Hope that helps. 

Taylor
